/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...all]': RouteRecordInfo<
      '/[...all]',
      '/:all(.*)',
      { all: ParamValue<true> },
      { all: ParamValue<false> },
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/guide/': RouteRecordInfo<
      '/guide/',
      '/guide',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/structure': RouteRecordInfo<
      '/guide/structure',
      '/guide/structure',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/guide/submit': RouteRecordInfo<
      '/guide/submit',
      '/guide/submit',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/problems/': RouteRecordInfo<
      '/problems/',
      '/problems',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resources/': RouteRecordInfo<
      '/resources/',
      '/resources',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resources/references': RouteRecordInfo<
      '/resources/references',
      '/resources/references',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/resources/tools': RouteRecordInfo<
      '/resources/tools',
      '/resources/tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/solutions/': RouteRecordInfo<
      '/solutions/',
      '/solutions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-press@0.27.0_@algolia+client-search@5.51.0_search-insights@2.17.3/node_modules/valaxy-theme-press/pages/[...all].vue': {
      routes:
        | '/[...all]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.27.0_@babel+parser@7.29.2_@types+markdown-it@14.1.2_@types+node@25.6.0_@vue+compiler_7zx6nqkvatejucsgghidrmqxky/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/guide/index.md': {
      routes:
        | '/guide/'
      views:
        | never
    }
    'pages/guide/structure.md': {
      routes:
        | '/guide/structure'
      views:
        | never
    }
    'pages/guide/submit.md': {
      routes:
        | '/guide/submit'
      views:
        | never
    }
    'pages/problems/index.md': {
      routes:
        | '/problems/'
      views:
        | never
    }
    'pages/resources/index.md': {
      routes:
        | '/resources/'
      views:
        | never
    }
    'pages/resources/references.md': {
      routes:
        | '/resources/references'
      views:
        | never
    }
    'pages/resources/tools.md': {
      routes:
        | '/resources/tools'
      views:
        | never
    }
    'pages/solutions/index.md': {
      routes:
        | '/solutions/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
